In [2]:
import numpy as np

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [3]:
x = np.arange(1, 21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
x[1:4, 2:5] # 2nd to 4th row, 3rd to 5th column

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [9]:
x[1:, 2:] # 2nd to last row, 3rd to last column

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [10]:
x[:3, 2:] # First to 3rd row, 3rd to last column

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [11]:
x[:, 2] # All rows, 2nd column (rank 1 array)

array([ 3,  8, 13, 18])

In [23]:
x = np.arange(0, 20).reshape(4,5)
y = np.copy(x[1:, 2:])
print(x, '\n\n', y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [25]:
indices = np.array([1, 3])
x[indices] # Rows 2 and 4

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [26]:
x[:, indices] # Columns 2 and 4

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [28]:
np.diag(x) # Diagonal of x

array([ 0,  6, 12, 18])

In [29]:
np.diag(x, k=1) # Diagonal of x above the main diagonal

array([ 1,  7, 13, 19])

In [30]:
np.diag(x, k=-1) # Diagonal of x below the main diagonal

array([ 5, 11, 17])

In [31]:
np.unique(np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]]))

array([1, 2, 3, 4, 5, 6])