In [1]:
import numpy as np

In [11]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [7]:
print('1st element of x: ', x[0])
print('2st element of x: ', x[1])
print('4st element of x: ', x[4])

1st element of x:  1
2st element of x:  2
4st element of x:  5


In [8]:
print('1st element of x: ', x[-5])
print('2st element of x: ', x[-4])
print('4st element of x: ', x[-1])

1st element of x:  1
2st element of x:  2
4st element of x:  5


In [9]:
x[3] = 20
x

array([ 1,  2,  3, 20,  5])

In [13]:
y = np.arange(1, 10).reshape(3, 3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print('Element (0, 0) of y: ', y[0, 0])
print('Element (0, 1) of y: ', y[0, 1])
print('Element (1, 2) of y: ', y[1, 2])

Element (0, 0) of y:  1
Element (0, 1) of y:  2
Element (1, 2) of y:  6


In [15]:
y[0, 0] = 20
y

array([[20,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
z = np.arange(0, 16).reshape(4, 4)
print(z)

z = np.delete(z, [0,4])
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15]


In [27]:
w = np.arange(0, 9).reshape(3, 3)
print(w)

print('\n', np.delete(w, 0, axis=0))

print('\n', np.delete(w, [0,2], axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[3 4 5]
 [6 7 8]]

 [[1]
 [4]
 [7]]


In [30]:
x = np.arange(1, 6)
print(np.append(x, 6))
print(np.append(x, [7, 8]))

[1 2 3 4 5 6]
[1 2 3 4 5 7 8]


In [35]:
y = np.arange(0, 9).reshape(3, 3)
print(np.append(y, [[10, 11, 12]], axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]]


In [39]:
z = np.arange(0, 9).reshape(3, 3)
print(np.append(z, [[10], [11], [12]], axis=1))

[[ 0  1  2 10]
 [ 3  4  5 11]
 [ 6  7  8 12]]


In [40]:
w = np.arange(0, 5)
print(np.insert(w, 2, [3, 4]))

[0 1 3 4 2 3 4]


In [48]:
w = np.arange(0, 6).reshape(2, 3)
print(np.insert(w, 1, [6, 7, 8], axis=0))

[[0 1 2]
 [6 7 8]
 [3 4 5]]


In [49]:
w = np.arange(0, 6).reshape(2, 3)
print(np.insert(w, 1, 5, axis=1))

[[0 5 1 2]
 [3 5 4 5]]


In [55]:
x = np.array([1, 2])
y = np.arange(3, 7).reshape(2, 2)
print(x, '\n')
print(y, '\n')
print(np.vstack((x, y)), '\n')
print(np.hstack((y, x.reshape(2, 1))))

[1 2] 

[[3 4]
 [5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[3 4 1]
 [5 6 2]]
