In [1]:
import numpy as np

In [12]:
x = np.arange(25).reshape(5, 5)
print(x, '\n')
print(x > 10, '\n')
print(x[x > 10])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]] 

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [13]:
x[(x > 10) & (x < 17)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [22]:
x = np.arange(5)
y = np.arange(3, 10)

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.setdiff1d(y, x))
print(np.union1d(x, y))

[3 4]
[0 1 2]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [23]:
x = np.random.randint(1, 11, size=(10,))
x

array([2, 6, 6, 2, 5, 4, 6, 1, 9, 1])

In [26]:
print(np.sort(x))
print(np.sort(np.unique(x)))

[1 1 2 2 4 5 6 6 6 9]
[1 2 4 5 6 9]


In [30]:
x = np.random.randint(1, 11, size=(5,5))
x

array([[ 4,  1,  6,  9,  8],
       [ 7,  5,  6,  8,  4],
       [ 8,  7,  3,  2,  6],
       [ 5,  1,  5,  5,  3],
       [10,  9,  1,  6,  6]])

In [33]:
print(np.sort(x, axis=0), '\n')
print(np.sort(x, axis=1))

[[ 4  1  1  2  3]
 [ 5  1  3  5  4]
 [ 7  5  5  6  6]
 [ 8  7  6  8  6]
 [10  9  6  9  8]] 

[[ 1  4  6  8  9]
 [ 4  5  6  7  8]
 [ 2  3  6  7  8]
 [ 1  3  5  5  5]
 [ 1  6  6  9 10]]


In [35]:
np.arange(1, 26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])