In [1]:
import numpy as np

list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np.array(list)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
zeros = np.zeros((3, 4))

print(zeros)
print(zeros.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


In [6]:
ones = np.ones((5, 3))

print(ones)
print(ones.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(5, 3)


In [7]:
fulls = np.full((2, 4), 10)

print(fulls)
print(fulls.shape)

[[10 10 10 10]
 [10 10 10 10]]
(2, 4)


In [8]:
id_matrix = np.eye(5)

print(id_matrix)
print(id_matrix.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)


In [9]:
diag_matrix = np.diag([10, 20, 30, 40, 50])

print(diag_matrix)
print(diag_matrix.shape)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]
(5, 5)


In [11]:
arange = np.arange(4, 9)

print(arange)

[4 5 6 7 8]


In [12]:
arange2 = np.arange(4, 25, 3)

print(arange2)

[ 4  7 10 13 16 19 22]


In [14]:
linspace = np.linspace(1, 25, 6)

print(linspace)

[ 1.   5.8 10.6 15.4 20.2 25. ]


In [19]:
x = np.arange(1, 21)
reshape_x = np.reshape(x, (4,5))
reshape_x2 = np.reshape(x, (10,2))

print(x)
print(reshape_x)
print(reshape_x2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [20]:
np.arange(20).reshape((4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
np.linspace(0, 50, 10).reshape((5, 2))

array([[ 0.        ,  5.55555556],
       [11.11111111, 16.66666667],
       [22.22222222, 27.77777778],
       [33.33333333, 38.88888889],
       [44.44444444, 50.        ]])

In [23]:
np.random.random((3, 3))

array([[0.03776979, 0.27667348, 0.97013867],
       [0.61471316, 0.17728988, 0.83776313],
       [0.72753844, 0.04097042, 0.44285513]])

In [24]:
np.random.randint(4, 15, (3, 3))

array([[ 8,  5, 12],
       [ 5,  7, 10],
       [ 8,  4,  5]])

In [25]:
np.random.normal(0, 0.1, (100, 100))

array([[ 1.11872178e-01, -2.52798939e-02,  4.94764360e-02, ...,
        -1.04273796e-01,  2.47124404e-02, -3.03523688e-02],
       [ 1.36293619e-01, -3.74635047e-02,  1.57860962e-01, ...,
         1.87160096e-01, -4.05823405e-03,  3.30877748e-02],
       [-1.32459355e-03, -2.17154100e-01, -1.00236225e-04, ...,
        -8.17232844e-02,  9.65322793e-02,  4.17952496e-02],
       ...,
       [-7.98310079e-02,  2.02269329e-01, -8.43395552e-02, ...,
         4.16525875e-03,  1.18351262e-01, -9.40147944e-02],
       [-1.78171887e-01, -4.19008035e-02, -1.33180200e-02, ...,
        -2.28984245e-02,  5.19214876e-02,  5.48655393e-02],
       [ 1.44173455e-01, -6.50639109e-02, -2.36368222e-01, ...,
        -1.45525088e-02,  3.95595963e-02, -1.41161320e-01]])

# Exercício

Using the Built-in functions you learned about on the previous page, create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive).

In [36]:
np.arange(2, 34, 2).reshape((4, 4))


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])