In [ ]:
%pip install numpy

In [2]:
import numpy as np

x = np.array([1, 2, 3])
print(x)
print(x.size)
print(x.shape)
print(x.dtype)
print(type(x))

np.save('test_array', x)

[1 2 3]
3
(3,)
int64
<class 'numpy.ndarray'>


In [3]:
print('mean: ', x.mean())
print('std: ', x.std())
print('max: ', x.max())
print('min: ', x.min())
print('# positive', (x > 0).sum())
print('# negative', (x < 0).sum())

mean:  2.0
std:  0.816496580927726
max:  3
min:  1
# positive 3
# negative 0


In [17]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y.size)
print(y.shape)
print(y.dtype)
print(type(y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
int64
<class 'numpy.ndarray'>


In [18]:
z = np.array(['1', '2', 'World'])

print(z)
print(z.size)
print(z.shape)
print(z.dtype)
print(type(z))


['1' '2' 'World']
3
(3,)
<U5
<class 'numpy.ndarray'>


In [19]:
v = np.array([1, 2.5, 3])

print(v)
print(v.size)
print(v.shape)
print(v.dtype)
print(type(v))

[1.  2.5 3. ]
3
(3,)
float64
<class 'numpy.ndarray'>


In [20]:
w = np.array([1, 2, 3], dtype=np.float64)

print(w)
print(w.size)
print(w.shape)
print(w.dtype)
print(type(w))

[1. 2. 3.]
3
(3,)
float64
<class 'numpy.ndarray'>


In [22]:
x2 = np.load('test_array.npy')

print(x2)

[1 2 3]
