In [1]:
import numpy as np

In [2]:
x = np.arange(4)
y = np.arange(4, 8)

print(x)
print(y)

[0 1 2 3]
[4 5 6 7]


In [3]:
print(x + y)
print(np.add(x, y))

[ 4  6  8 10]
[ 4  6  8 10]


In [4]:
print(x - y)
print(np.subtract(x, y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]


In [5]:
print(x * y)
print(np.multiply(x, y))

[ 0  5 12 21]
[ 0  5 12 21]


In [6]:
print(x / y)
print(np.divide(x, y))

[0.         0.2        0.33333333 0.42857143]
[0.         0.2        0.33333333 0.42857143]


In [7]:
X = np.arange(4).reshape(2, 2)
Y = np.arange(4, 8).reshape(2, 2)

print(X)
print(Y)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [9]:
print(np.sqrt(x))
print(np.power(x, 2))

[0.         1.         1.41421356 1.73205081]
[0 1 4 9]


In [10]:
print('Average of all elements in X:', X.mean())
print('Average of columns in X:', X.mean(axis=0))
print('Average of rows in X:', X.mean(axis=1))

Average of all elements in X: 1.5
Average of columns in X: [1. 2.]
Average of rows in X: [0.5 2.5]


In [13]:
X = np.arange(0,9).reshape(3,3)
Y = np.arange(0,3).reshape(3,1)

print(X)
print(Y)
print(X + Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


# Broadcasting

Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.

https://numpy.org/devdocs/user/basics.broadcasting.html

In [28]:
X = np.ones((4, 4), dtype=int) * np.array([1, 2, 3, 4]).reshape(4)

print(X)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
